### PR TITLE
add reference to examples in README

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
help newcomers orient themselves how to actually use `rules_nixpkgs`

### CODE REVIEW

**Review by steshaw — APPROVED** [review]
Looks good.

A nice follow-up might be to move the multiline strings containing strings to external `.md` files to make them easier to edit (with editor supported modes). If possible of course.

**Comment by fricklerhandwerk** [comment]
It is possible and we had this until recently, but this made documentation rendering fairly complex as it required more build steps, and made the source harder to navigate. It's of course a trade-off. Right now it is not that much text and everything is self-contained in between the actual code, so it seems appropriate to me.

**Comment by steshaw** [comment]
@fricklerhandwerk I'd like to take a look at the previous complexity. Can you point me at a commit?

**Comment by fricklerhandwerk** [comment]
@steshaw #202 and [this specifically](https://github.com/tweag/rules_nixpkgs/pull/202/files#diff-f8ca881095fec0f1448b91970239419034e141839711f602e8cbc5131d1c061fL52-L115).

**Comment by steshaw** [comment]
Thanks. I see! That does indeed look complicated. What's more, it doesn't help with editor tooling to have the markdown file in a template file `.md.tpl`. The complexity seems to be related to processing the `.tpl` file using AWK. I was thinking more of a `README.top.md` and `README.bottom.md` and then just concatenating those with the generated API docs with `cat`. That might be awkward though. It is a trade-off.

**Pull request merged**
