### PR TITLE
Introduce a `data` attribute to `nixpkgs_package`

### PR DESCRIPTION
**Pull request by guibou**
This is a solution for #17, the new `data` attribute references all the files
needed to execute the nix expression, hence invalidating cache if they are
modified.

### CODE REVIEW

**Comment by guibou** [comment]
@mboes the point of using `data` was that the "root" nix file was specified in `nix_file` and all the dependencies are in `data`. I can rename it `srcs` if you wish.

But what about `nix_file`, should we keep it or delete it? If we remove it, which file in `srcs` should be used? The order is not reliable because user may use `glob` to fill `srcs`. Should we use `srcs` AND `nix_file`?

**Comment by Fuuzetsu** [comment]
@mboes I don't think the issue is only up to `nix` files and data was a better name. The nix file itself can refer to arbitrary files: if the arbitrary file changes and the nix file doesn't, currently bazel will not re-run the role. I thought this was the original problem. Of course these arbitrary files could be other nix files but that's only a subset of possible inputs.

**Comment by guibou** [comment]
@mboes name changed from `data` to `srcs`. And one of `repository` or `path` attribute should be setup.

**Comment by mboes** [comment]
@Fuuzetsu `data` is typically used for runtime dependencies. But there is no "runtime" here, and these are dependencies of the package metadata description. Technically the `build_file` could also have dependencies, since it can `load()`. So opting for renaming to `nix_file_deps`.

**Pull request merged**
