### PR TITLE
Rules rust 0.1.0

### PR DESCRIPTION
**Pull request by betaboon**

### CODE REVIEW

**Comment by aherrmann** [comment]
Looks like this addresses https://github.com/tweag/rules_nixpkgs/issues/205.

**Comment by fricklerhandwerk** [comment]
@betaboon [We enabled CI runs on PRs](https://github.com/tweag/rules_nixpkgs/pull/206). Could you please force-push to trigger CI?

**Review by fricklerhandwerk — APPROVED** [review]

**Comment by fricklerhandwerk** [comment]
@betaboon Thank you very much!

**Comment by betaboon** [comment]
Thanks for the speedy merge

**Pull request merged**
