### PR TITLE
README: add instructions for bazel6 + Java

### LINKED ISSUE #357: Include Java Bazel 6 configuration in README
**Describe the bug**
The section on Java configuration in the README does not yet reflect the required configuration for Bazel version 6, while this configuration is already present in the example under `examples/toolchains/java`.

**To Reproduce**
n/a

**Expected behavior**
The README should cover the Bazel 6 configuration for Java.

**Environment**
 - OS name + version: n/a
 - Version of the code: 902c31a

### PR DESCRIPTION
**Pull request by motiejus**
Fixes #357

### CODE REVIEW

**Review by aherrmann — APPROVED** [review]
Thank you @motiejus!

**Review by benradf — APPROVED** [review]

**Comment by benradf** [comment]
Looks like CI is failing because the README needs to be updated:
```
Test output for //:check-README.md:
  README.md is not up to date.
  Please update it using the following command:
  
  bazel run //:update-README.md
```

**Comment by benradf** [comment]
Yeah, I realised after I commented that it was a bit more complicated than just running `bazel run //docs:update-README.md`.

I think if you move your change to [toolchains/java/java.bzl](https://github.com/tweag/rules_nixpkgs/blob/master/toolchains/java/java.bzl#L172), and then run the update command it should work:
```
# From the root of rules_nixpkgs:
nix-shell --run 'cd docs; bazel run //:update-readme'
```

**Comment by benradf** [comment]
@motiejus, I manually updated `toolchains/java/README.md` to get this to pass CI. Normally this would be done with `bazel run //docs:update-README.md` in the `toolchains/java` workspace.

The `README.md` file in the root workspace is updated with `bazel run //:update-README.md` in the `docs/` workspace (which you did correctly). Sorry for the confusion here, turns out there are two `README` files with separate rules to update them.

**Pull request merged**
