### PR TITLE
vendor large parts of @bazel_tools//tools/cpp

### LINKED ISSUE #612: almost all of `@bazel_tools//tools/cpp` may not exist for Bazel@8.0.0rc4
Hello,

I've just received an email from bazelbuild/bazel-central-registry saying that the module I maintain contains errors for Bazel@8.0.0rc4. The build output says that [this import](https://github.com/tweag/rules_nixpkgs/blob/668609f0b3627751651cb325166d0e95062be3f7/core/util.bzl#L1) may not exist.

Build run: https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/72#019367bc-a445-4f6b-8c2b-0413f2287689

Error message:
```
(09:32:44) ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/util.bzl", line 1, column 55, in <toplevel>
		load("@bazel_tools//tools/cpp:lib_cc_configure.bzl", "get_cpu_value")
Error: file '@bazel_tools//tools/cpp:lib_cc_configure.bzl' does not contain symbol 'get_cpu_value'
(09:32:44) ERROR: Analysis of target '//:spec' failed; build aborted: Error loading '@@rules_nixpkgs_core+//extensions:package.bzl' for module extensions, requested by /var/lib/buildkite-agent/builds/bk-docker-2fzt/bazel-org-repo-root/output/rules_elm-1.0.1/examples/elm-test/MODULE.bazel:105:24: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/extensions/package.bzl:6:6: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/nixpkgs.bzl:36:5: initialization of module 'util.bzl' failed: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/extensions/package.bzl:6:6: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/nixpkgs.bzl:36:5: initialization of module 'util.bzl' failed
```

Helpful links:
- [commit](https://github.com/bazelbuild/bazel/commit/1c4e78a9ceab9794140324d64833c628e382a3da) where `@bazel_tools//tools/cpp` was moved away
- [commit](https://github.com/bazelbuild/rules_cc/commit/c2549f6eb07ce00e529b84f9b9f1b31135a9ff77) where the same code was added to rules_cc

### PR DESCRIPTION
**Pull request by malt3**
Most of @bazel_tools//tools/cpp was removed from @bazel_tools and moved into a private package in rules_cc in Bazel 8.

It looks like some parameters of `cc_toolchain_config` where added over the years and are not available in all versions of Bazel.
I ended up doing [some clever version checks](https://github.com/tweag/rules_nixpkgs/pull/622/commits/32c48867931852b2678425323b29207e3c0f4646) when selecting the right version of `unix_cc_toolchain_config.bzl`.

Fixes #612

### CODE REVIEW

**Review by tshaynik — APPROVED** [review]
Looks great!

**Comment by kczulko** [comment]
@malt3 
Thank you for this! Do you plan to drop a BCR release soon?

Regards,
Karol

**Comment by malt3** [comment]
@kczulko we do! If possible, we'd like to fix #623 first. Any Nix + macOS sdk knowledge would help us there.

**Comment by kczulko** [comment]
Thx, got it. Sorry but I'm a core x86_64-linux user.

**Pull request merged**
