### PR TITLE
Update used Bazel version to 5

### PR DESCRIPTION
**Pull request by AleksanderGondek**
This pull requests will:
* Ensure all invocations are using Bazel version >= 5.0.0
* Ensure all references to nixpkgs will use channel 22.05
* Ensure rules_java are using java toolchains
* Update used version of openJDK to 11
* Update io_bazel_startdoc to version 0.5.1 (required for Bazel 5 compatibility)
* Update rules_java to version 5.0.0 (required for Bazel 5 compatibility)
* Update README.md's

### CODE REVIEW

**Comment by AleksanderGondek** [comment]
Hi @avdv @aherrmann,
If you guys would have some free time, I would greatly appreciate your help in finding the culprit of CI-related issues. They do not seem to appear on "freshly minted" VMs / containers which I spring to action.

When running locally `$ NIX_PATH=nixpkgs=./core/nixpkgs.nix nix-shell --pure --keep GITHUB_REPOSITORY --run 'bash .github/build-and-test`:
- Ubuntu 20.04/22.04: Status code 0, no failures
- NixOS 22.05: Status code 1, only failure stemms from the fact that ijar does not work on NiXOS (every other test passes)

**Comment by aherrmann** [comment]
@AleksanderGondek Thanks for looking into this! I took a look at the configuration issue, and I think I found a reasonable way to make the configuration consistent across the sub-repositories and examples. I've pushed the necessary changes to this PR.

**Comment by aherrmann** [comment]
It works in the `push` pipelines but not in the `pull_request` pipelines. So, it's probably because the credentials are missing in the `pull_request` one. Since it grants write access to the remote cache, that seems like a reasonable restriction. Perhaps we could use a read-only key in the public configuration.

**Comment by AleksanderGondek** [comment]
Hi guys,
Can I do anything to help you out in settings things up or moving on with the PR ? :)

**Review by aherrmann — APPROVED** [review]

**Comment by aherrmann** [comment]
Thanks for the ping. I've asked around and looked into the [Github action docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories) and there doesn't seem to be any way to expose secrets to GH action runs triggered from forks. So, until we find something better, I've disabled the `pull_request` trigger. In the meantime, as in the past, reviewers will have to push to the tweag org to trigger CI runs on external PRs.

**Comment by aherrmann** [comment]
>  I did not mean to hurry anyone, although I do appreciate your prompt response! :)

No worries, your ping was perfectly timed: I had a couple minutes available. :)

**Pull request merged**
