### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by prednaz**
Creates release 0.11.0.

The next steps are:
- [ ] Review & Merge this PR.
- [ ] Publish the draft release.
- [ ] Push a release v0.11.0 tag to the merge commit of this PR.
- [ ] Get rules_nixpkgs_core 0.11.0 merged into the BCR.

### CODE REVIEW

**Comment by prednaz** [comment]
i wrote the `CHANGELOG.md` based on the output of `git o --grep='pull request' --merges --grep='#' --grep='pull request' master ^v0.10.0 | grep -v 'tweag/dependabot/github_actions/' | grep -v 'tweag/update_flake_lock_action'`.

i tried to filter out changes that are not user facing. i was unsure about https://github.com/tweag/rules_nixpkgs/pull/472 and https://github.com/tweag/rules_nixpkgs/pull/453. they are not user facing as far as i can tell.

**Review by benradf — APPROVED** [review]
Looks good to me. Thanks for doing this new release!

**Review by avdv — CHANGES_REQUESTED** [review]
Thank you, LGTM.

But I tested https://github.com/tweag/rules_haskell/pull/2136 against these changes and I need to get one more fix in...

**Review by avdv — APPROVED** [review]
:+1:  this is good now, PR #489 merged.

**Pull request merged**
