### PR TITLE
Fix call to `repository_ctx.file` using `nix_file_content` with `nixpkgs_local_repository`

### LINKED ISSUE #140: Test the `nix_file_content attribute` of the `nixpkgs_local_repository` rule
**Describe the bug**
The attribute `nix_content_file` is not tested and when using it, I got the following error message:
```ERROR: An error occurred during the fetch of repository 'nixpkgs':
   file() got named argument for positional-only parameter 'path'
```

**To Reproduce**
Add a repository rule using the attribute `nix_content_file`.

**Expected behavior**

**Environment**
 - OS name + version:
 - Version of the code:

**Additional context**

### PR DESCRIPTION
**Pull request by avdv**
```
ERROR: An error occurred during the fetch of repository 'nixpkgs':
   Traceback (most recent call last):
	File "/home/claudio/.cache/bazel/_bazel_claudio/c7ff5b30a595e0e5def985dcafaa7d4c/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl", line 54, column 28, in _nixpkgs_local_repository_impl
		repository_ctx.file(
Error in file: file() got named argument for positional-only parameter 'path'
```

Fixes #140.

### CODE REVIEW

**Comment by avdv** [comment]
Would be nice to add some example / test for this...

**Comment by fricklerhandwerk** [comment]
How did you reproduce this? We have [repository rules](https://github.com/tweag/rules_nixpkgs/blob/9cfa583faae686b9868a8d67e91fe8ceb4d51914/WORKSPACE#L81-L87) used for tests that exercise `nix_file_content`.

**Comment by fricklerhandwerk** [comment]
That makes for a test.
```patch
diff --git a/WORKSPACE b/WORKSPACE
index 82dc73e..2ae774a 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -51,6 +51,12 @@ nixpkgs_local_repository(
     nix_file_deps = ["//:nixpkgs.json"],
 )
 
+nixpkgs_local_repository(
+    name = "local_nixpkgs",
+    nix_file_content = "import <nixpkgs> { config = {}; overlays = []; }",
+    nix_file_deps = ["//:nixpkgs.json"],
+)
+
 # This is the commit introducing a Nix version working in the Bazel
 # sandbox
 nixpkgs_git_repository(
@@ -72,6 +78,12 @@ nixpkgs_package(
     repositories = {"nixpkgs": "@remote_nixpkgs"},
 )
 
+nixpkgs_package(
+    name = "nixpkgs-local-repository-test",
+    attribute_path = "hello",
+    repositories = {"nixpkgs": "@local_nixpkgs"},
+)
+
 nixpkgs_package(
     name = "hello",
     # Deliberately not repository, to test whether repositories works.
@@ -80,7 +92,7 @@ nixpkgs_package(
 
 nixpkgs_package(
     name = "expr-test",
-    nix_file_content = "let pkgs = import <nixpkgs> { config = {}; overlays = []; }; in pkgs.hello",
+    nix_file_content = "with import <nixpkgs> {}; hello",
     nix_file_deps = ["//:nixpkgs.json"],
     # Deliberately not @nixpkgs, to test whether explict file works.
     repositories = {"nixpkgs": "//:nixpkgs.nix"},
diff --git a/tests/BUILD.bazel b/tests/BUILD.bazel
index 7e02357..a9ed1d2 100644
--- a/tests/BUILD.bazel
+++ b/tests/BUILD.bazel
@@ -27,6 +27,7 @@ expand_location_unit_test_suite()
         "nix-file-test",
         "nix-file-deps-test",
         "nixpkgs-git-repository-test",
+        "nixpkgs-local-repository-test",
         "relative-imports",
     ]
 ] + [
```

But it produces a new error...
```
ERROR: An error occurred during the fetch of repository 'local_nixpkgs':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_tweag/0060e94eb8cc5b3692d332a00756b8a8/external/rules_nixpkgs_core/nixpkgs.bzl", line 102, column 61, in _nixpkgs_local_repository_impl
		repository_ctx.file("nix-file-deps", content = "\n".join(repository_files))
Error in join: expected string for sequence element 0, got 'path'
```

**Comment by avdv** [comment]
> That makes for a test.

Thank you, @fricklerhandwerk  I just re-used the existing nixpkgs definition for the sake of simplicity, and because I did not want to rely on global `<nixpkgs>`.



> But it produces a new error...
> 
> ```
> ERROR: An error occurred during the fetch of repository 'local_nixpkgs':
>    Traceback (most recent call last):
> 	File "/private/var/tmp/_bazel_tweag/0060e94eb8cc5b3692d332a00756b8a8/external/rules_nixpkgs_core/nixpkgs.bzl", line 102, column 61, in _nixpkgs_local_repository_impl
> 		repository_ctx.file("nix-file-deps", content = "\n".join(repository_files))
> Error in join: expected string for sequence element 0, got 'path'
> ```

Fixed too.

**Review by fricklerhandwerk — APPROVED** [review]

**Pull request merged**
